---
- name: Ensure that logfile directory exists
  ansible.builtin.file:
    path: "{{ node_exporter_log_path_mac }}"
    owner: "{{ node_exporter_user }}"
    mode: "0755"
    state: directory

- name: Set node_exporter_exe fact
  ansible.builtin.set_fact:
    node_exporter_exe: "{{ ansible_pkg_mgr_bin }}/node_exporter"

- name: Initialize fact for node_exporter extra arguments
  ansible.builtin.set_fact:
    node_exporter_args_mac: ""

- name: Build node_exporter extra arguments
  ansible.builtin.set_fact:
    node_exporter_args_mac: >
      {{ node_exporter_args_mac }}
      <string>{{ node_exporter_arg }}</string>
  with_items: "{{ node_exporter_args }}"
  loop_control:
    loop_var: node_exporter_arg

- name: Ensure LaunchDaemon plist file exists
  become: true
  ansible.builtin.template:
    src: "{{ node_exporter_ident }}.plist.j2"
    dest: "{{ node_exporter_plist }}"
    mode: "0644"
  register: node_exporter_plist_template

- name: Start node_exporter daemon
  become: true
  community.general.launchd:
    name: "{{ node_exporter_ident }}"
    state: started
  when: node_exporter_plist_template is changed

